SANITY_CHECK_LIVE_PORTS:
  - host: localhost
    port: 80
    message: "Load balancer does not respond on port 80."
  - host: localhost
    port: 443
    message: "Load balancer does not respond on port 443."

TARSNAP_BACKUP_FOLDERS: /etc/letsencrypt

LOAD_BALANCER_OPS_EMAIL: "{{ OPS_EMAIL }}"
