- name: Install Python 2
  hosts: load-balancer:rabbitmq
  become: true
  gather_facts: false
  tasks:
    - raw: "[ -e /usr/bin/pyton ] || sudo apt-get update -qq && sudo apt-get install -qq python"

- name: Set up Dalite servers
  hosts: dalite
  become: true
  roles:
    - name: common-server
      TARSNAP_KEY: "{{ DALITE_LOGROTATE_TARSNAP_KEY }}"
      TARSNAP_KEY_REMOTE_LOCATION: "/root/tarsnap-logrotate.key"
      TARSNAP_BACKUP_PRE_SCRIPT: "/usr/local/sbin/dalite-pre-backup.sh"
      TARSNAP_BACKUP_SCRIPT_LOCATION: "{{ DALITE_TARSNAP_BACKUP_SCRIPT }}"
      TARSNAP_ARCHIVE_NAME: "dalite-logs"
      TARSNAP_CACHE: "/var/cache/tarsnap-logrotate"
      TARSNAP_BACKUP_FOLDERS: "{{ DALITE_LOG_DOWNLOAD_LOG_DIR }} {{ DALITE_LOG_DOWNLOAD_DB_DIR }}"
      TARSNAP_BACKUP_SNITCH: "{{ DALITE_LOG_TARSNAP_SNITCH }}"
      # Backup of logs is initiated by logrotate, which incidentally
      # also creates data to be backed up.
      TARSNAP_CRONTAB_STATE: "absent"
    - forward-server-mail
    - dalite
    - backup-swift-container

- name: Set up load-balancing servers
  hosts: load-balancer
  become: true
  roles:
    - common-server
    - forward-server-mail
    - load-balancer

- name: Set up rabbitmq servers
  hosts: rabbitmq
  become: true
  roles:
    - common-server
    - forward-server-mail
    - rabbitmq
