- name: Set up servers
  hosts: all
  become: true
  roles:
    - name: common-server
      TARSNAP_KEY: "{{ DALITE_LOGROTATE_TARSNAP_KEY }}"
      TARSNAP_KEY_REMOTE_LOCATION: "/root/tarsnap-logrotate.key"
      TARSNAP_BACKUP_PRE_SCRIPT: "/usr/local/sbin/dalite-pre-backup.sh"
      TARSNAP_BACKUP_SCRIPT_LOCATION: "{{ DALITE_TARSNAP_BACKUP_SCRIPT }}"
      TARSNAP_ARCHIVE_NAME: "dalite-logs"
      TARSNAP_CACHE: "/var/cache/tarsnap-logrotate"
      TARSNAP_BACKUP_FOLDERS: "{{ DALITE_LOG_DOWNLOAD_LOG_DIR }} {{ DALITE_LOG_DOWNLOAD_DB_DIR }}"
      TARSNAP_BACKUP_SNITCH: "{{ DALITE_LOG_TARSNAP_SNITCH }}"
      # Backup of logs is initiated by logrotate, which incidentally
      # also creates data to be backed up.
      TARSNAP_CRONTAB_STATE: "absent"
    - name: forward-server-mail

- name: Set up dalite
  hosts: dalite
  become: true
  roles:
    - name: dalite

- name: Enable swift container on dalite
  hosts: dalite
  become: true
  roles:
    - name: backup-swift-container
      TARSNAP_CACHE: "/var/cache/tarsnap-swift"
      BACKUP_SWIFT_TARSNAP_KEY: "{{ DALITE_TARSNAP_SWIFT }}"
      BACKUP_SWIFT_RC: "{{ DALITE_SWIFT_BACKUP_RC }}"