- name: Install Python 2 on target machine
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - raw: sudo apt-get update -qq && sudo apt-get install -qq python

- name: Set up load balancers
  hosts: load-balancer
  become: true
  roles:
    - name: common-server
      COMMON_SERVER_NO_BACKUPS: true
    - forward-server-mail
    - load-balancer
