SANITY_CHECK_LIVE_PORTS:
  - host: localhost
    port: 5671
    message: "RabbitMQ does not respond on port 5671."
  - host: localhost
    port: 15671
    message: "RabbitMQ management does not respond on port 15671."

TARSNAP_BACKUP_FOLDERS: "{{ RABBITMQ_EXPORT_DIR }} /etc/rabbitmq /etc/letsencrypt"
TARSNAP_BACKUP_PRE_SCRIPT: "{{ RABBITMQ_SCRIPTS_DIR }}/{{ RABBITMQ_BACKUP_COMMAND }}"
