DALITE_SERVER_DOMAIN: '{{ inventory_hostname }}'

DALITE_REPOSITORY_VERSION: "jbzdak/dalite-harvardx-ansible"

DALITE_USER_NAME: "dalite"
DALITE_USER_HOME: "/home/{{ DALITE_USER_NAME }}"
DALITE_APP_LOCATION: "{{ DALITE_USER_HOME }}/repository"
DALITE_VENV: "{{ DALITE_USER_HOME }}/venv"
DALITE_PYTHON: "{{ DALITE_VENV }}/bin/python"
DALITE_MANAGE_PY: "{{ DALITE_PYTHON }} {{ DALITE_APP_LOCATION }}/manage.py "

DALITE_TARSNAP_BACKUP_SCRIPT: "/usr/local/sbin/backup-logs.sh"
DALITE_LOG_DOWNLOAD_USER: logs-download
DALITE_LOG_DOWNLOAD_USER_HOME: "/home/{{ DALITE_LOG_DOWNLOAD_USER }}"
DALITE_LOG_DOWNLOAD_LOG_DIR: "{{ DALITE_LOG_DOWNLOAD_USER_HOME }}/logs"
DALITE_LOG_DOWNLOAD_DB_DIR: "{{ DALITE_LOG_DOWNLOAD_USER_HOME }}/db"

SANITY_CHECK_LIVE_PORTS:
  - host: localhost
    port: 80
    message: "Dalite http service is down"
  - host: localhost
    port: 443
    message: "Dalite https service is down"
  - host: "{{ MYSQL_DALITE_HOST }}"
    port: 3306
    message: "Dalite has no connection to mysql"
  - host: localhost
    port: 8080
    message: "Dalite gunicorn is down"

SANITY_CHECK_SUBJECT: '[Dalite] Sanity check problems'

SANITY_CHECK_COMMANDS:
  - command: "{{ DALITE_MANAGE_PY }} sanity_check"
    message: "Sanity check failed for Dalite. Is database accessible?"

TARSNAP_KEY: "{{ DALITE_LOGROTATE_TARSNAP_KEY }}"
TARSNAP_KEY_REMOTE_LOCATION: "/root/tarsnap-logrotate.key"
TARSNAP_BACKUP_PRE_SCRIPT: "/usr/local/sbin/dalite-pre-backup.sh"
TARSNAP_BACKUP_SCRIPT_LOCATION: "{{ DALITE_TARSNAP_BACKUP_SCRIPT }}"
TARSNAP_ARCHIVE_NAME: "dalite-logs"
TARSNAP_CACHE: "/var/cache/tarsnap-logrotate"
TARSNAP_BACKUP_FOLDERS: "{{ DALITE_LOG_DOWNLOAD_LOG_DIR }} {{ DALITE_LOG_DOWNLOAD_DB_DIR }}"
TARSNAP_BACKUP_SNITCH: "{{ DALITE_LOG_TARSNAP_SNITCH }}"
# Backup of logs is initiated by logrotate, which incidentally
# also creates data to be backed up.
TARSNAP_CRONTAB_STATE: "absent"

BACKUP_SWIFT_CONTAINER: "{{ DALITE_MEDIA_CONTAINER }}"
BACKUP_SWIFT_LOCAL_DIR: '/var/cache/dalite-swift-backup'
BACKUP_SWIFT_BACKUP_NAME: 'dalite-swift-backup'
BACKUP_SWIFT_DEST: '/usr/local/sbin/backup-container.sh'
BACKUP_SWIFT_CACHE: "/var/cache/tarsnap-swift"
BACKUP_SWIFT_TARSNAP_KEY: "{{ DALITE_TARSNAP_SWIFT }}"
BACKUP_SWIFT_RC: "{{ DALITE_SWIFT_BACKUP_RC }}"
